name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout test repo (trenutni repo)
      - uses: actions/checkout@v4

      # Checkout API repo
      - name: Checkout API repo
        uses: actions/checkout@v4
        with:
          repository: nejlaBelagosi/Tour_and_Travel_BiH
          path: TourAndTravelBiH
          token: ${{ secrets.GITHUB_TOKEN }}

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # koristi verziju koju API koristi

      # Build i start ASP.NET Core API
      - name: Build and run API
        run: |
          dotnet restore ./TourAndTravelBiH/TourAndTravelBiH/TourAndTravelBiH.csproj
          dotnet build ./TourAndTravelBiH/TourAndTravelBiH/TourAndTravelBiH.csproj --configuration Release
          dotnet run --project ./TourAndTravelBiH/TourAndTravelBiH/TourAndTravelBiH.csproj &
          sleep 15   # čekamo da API bude dostupan

      # Install Postman CLI
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      # Login Postman CLI
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      # Run Postman tests
      - name: Run API tests
        run: |
          postman collection run "48284099-76dc0f0a-693f-48e7-9fbc-fb65a262b5c7" \
          -e "48284099-1a85045b-9055-4e34-8350-cac0d14971be"
